---
title: "4. Bluestem Data Assignment"
---

<ul class="pager">
  <li class="previous"><a href="lab1_3_finch.html">&larr; Part 3. Finch Data Example</a></li>
</ul>

In Part 4, you will apply what you have learned to the bluestem variation data you collected at the Regional Science Center. You will create a new R script, read the bluestem data into R, plot histograms of plant height and rame length, estimate the means of those variables, plot them on bar charts.

Jump to section:

- [Your assignment]
    - [Step 1. Download the assignment template]
    - [Step 2. Download the bluestem data]
    - [Step 3. Create a script for plant height]
    - [Step 4. Repeat for rame length]
    - [Step 5. Write figure legends]
    - [Step 6. Write a RESULTS section]
    - [Step 7. Upload Word doc to D2L]
- [Saving your files]


### Your assignment

Your assignment is to generate figures and statistical analyses that answer the following question:

<blockquote class="text-success">Do plant height or rame length of Big Bluestem (<i>Andropogon gerardii</i>) plants vary between lowland and upland sites?</blockquote>

We recommend the following steps for completing your assignment.

#### Step 1. Download the assignment template

Download this Microsoft Word document:

<a href="lab1_assignment_template.docx"><i class="fas fa-file-word fa-5x"></i></a>

Steps 2 through 6 will walk you through how to modify the document so it uses your figures and text. When done, the document will contain the following:

1. A histogram of plant heights
2. A bar chart of plant heights
3. A histogram of rame lengths
4. A bar chart of rame lengths
5. Four figure legends, one for each of the figures listed above.
6. A section titled **RESULTS** which includes:
    - A paragraph describing the difference in plant heights between lowland and upland areas, citing the first two figures and giving the results of the plant height *t*-test.
    - A paragraph describing the difference in rame lengths between lowland and upland areas, citing the last two figures and giving the results of the rame length *t*-test.

When you're done, you will upload this document to D2L (see below for instructions).

#### Step 2. Download the bluestem data

Your assignment involves plotting and analyzing the data on instraspecific variation in big bluestem (*Andropogon gerardii*) plants that you collected during a field trip to the Regional Science Center. All the data were entered onto a single Excel spreadsheet.

Each row in the dataset represents an individual plant.

The variables in the dataset are:

- **location** ("lowland" vs. "upland")
- **plant_height** (plant height measured in cm)
- **rame_length** (rame length measured in mm)
- **section** (name of the section the data collector was in)

Download the bluestem dataset:

<a href="bluestem_data.xlsx"><i class="fas fa-file-excel fa-5x"></i></a>

Don't forget to move the file to your project directory after downloading it, or your code won't work.

#### Step 3. Create a script for plant height

It's always easier to modify existing code than create new code from scratch. 

For this assignment, you can use the script you just created to analyze **beak length** as a starting point.

1. Create a new R script, save it as `plant_height.R`
2. [Copy code from beak length script  &rarr;](lab1_beak_length_script.html)
3. Use "find and replace" (the magnifying glass on the Source tab toolbar) to modify the script.
    - replace `finches` with `bluestem`
    - replace `beak_length` with `plant_height`
    - replace `outcome` with `location`
    - replace `died` with `lowland` and replace `survived` with `upland`
    - change the x- and y-axis labels on the histogram
    - change the x- and y-axis labels on the bar chart
    - change the name of the file you save the histogram as
    - change the name of the file you save the bar chart as
4. Save the `plant_height.R` script
5. Run the `plant_height.R` script, one line at a time, watching for errors. If you performed step 3 correctly, you shouldn't get any errors.
6. Insert the figures into your word document
    - Open your project folder in the Finder. 
    - Open your Word document.
    - Drag the figures from the Finder into your open Word document.

#### Step 4. Repeat for rame length

Now you can repeat the same process for rame length.

Create a new R script, save it as `rame_length.R`, and paste in the code from `plant_height.R`.

This time you only need to:

1. replace `plant_height` with `rame_length`
2. change the axis labels
3. change the file names for saving
4. change the titles (e.g. **Figure 1** becomes **Figure 3**, and **2** becomes **4**)


#### Step 5. Write figure legends

Write figure legends for each figure in your Word document.

For reference, here are the figure legends for the finch beak length analysis again:

<blockquote class="text-info">Figure 1. <strong>Distribution of beak lengths among medium ground finches (<i>Geospiza fortis</i>) grouped by survival outcome during the 1977 drought on Daphne Major, Galapagos archipelago.</strong> Each sample consisted of 50 individuals. Birds were banded and measured during 1975-1977 and resighted in 1978.</blockquote>

<blockquote class="text-info">Figure 2. <strong>Mean beak length varied between medium ground finches (<i>Geospiza fortis</i>) that survived or died during the 1977 drought on Daphne Major, Galapagos archipelago.</strong> Each sample consisted of 50 individuals. Birds were banded and measured during 1975-1977 and resighted in 1978. Error bars represent 95% confidence intervals.</blockquote>

For tips on how to write a good figure legend, see [Writing an Effective Figure Legend](https://www.aje.com/en/arc/writing-effective-figure-legend/). In general, a figure legend should provide the following parts:

- Title: A brief title that applies to the entire figure, including all panels.
- Materials and methods: A description of the techniques used.
- Results: A statement of the results that can be gleaned from the particular figure.
- Definitions: An explanation of features in the figure.

#### Step 6. Write a RESULTS section

Write a RESULTS section as you might for a report or peer-reviewed article. This section should include:

- A paragraph describing the difference in plant heights between lowland and upland areas, citing the first two figures and giving the results of the plant height *t*-test.
- A paragraph describing the difference in rame lengths between lowland and upland areas, citing the last two figures and giving the results of the rame length *t*-test.

For reference, here is the paragraph we wrote for the beak length analysis:

<blockquote class="text-info">Birds that survived the 1977 drought generally had longer beaks than those that died (Fig. 1). Mean beak lengths were 11.1 mm in survivors and 10.5 mm in non-survivors (Fig. 2).  This difference was stastistically significant according to a Welch's two-sample t-test assuming unequal variances (*t*=3.6335, *df*=94.807, *p*=0.0004539).</blockquote>

#### Step 7. Upload Word doc to D2L

Once you have all the components in your Word document, save it and upload it to the Assignment area of your LAB (not lecture) site on [D2L](https://mnstate.learn.minnstate.edu/).

### Saving your files

If you want to save what you have done so you can work on it later, here is the best option:

1. Go to [Microsoft Office 360](https://www.mnstate.edu/it/office365/)
2. Click the link **Go to the Office 365 site**.
3. Log in to  with your StarID
4. Click the **OneDrive** Logo
3. Drag your Project folder from the Finder onto the area that says "Drag Files Here"

You may get an error message that it could not upload files starting with a dot ("."), e.g. .Rprofile. Ignore that warning, those files are not important.

To work on your files again:

1. Log in to [Microsoft Office 360](https://www.mnstate.edu/it/office365/) with your StarID
2. Click **OneDrive**
2. Click the check box next to your Project Folder
3. Click the **Download** button
4. Navigate to your **Downloads** folder in the Finder
5. If you don't see your Project folder there, but you do see a file ending in .zip, click that file and it will extract your Project folder.
6. Start RStudio
7. Open your Project using one of the methods described in [Part 1](lab1_1_rstudio.html).

An alternative to using OneDrive is to put your files on a USB storage device.

<ul class="pager">
  <li class="previous"><a href="lab1_3_finch.html">&larr; Part 3. Finch Data Example</a></li>
</ul>