---
title: "Data Lab 2"
---

In this lab you will apply what you learned in [Data Lab 1](lab1.html) to analyze the fast plant data generated by the class this semester.

Remember, the question you are trying to answer is:

<blockquote class="text-success">Does the number of trichomes on Fast Plants (<i>Brassica rapa</i>) plants vary between the F0 (parent) and F1 (offspring) generations.</blockquote>

The results of this assignment will form the RESULTS section of your **Fast Plant Lab Report**.

#### Your assignment

Your object in this lab is to generate the results that will answer this question, specifically:

- A histogram showing how the distribution of numbers of trichomes varied between generations
- A bar chart showing how the mean number of trichomes varied between generations. Include a 95% confidence interval around the means.
- Figure legends describing these two figures.
- A paragraph describing the results of the analysis, including the results of a *t*-test to test for a difference between the means.

To answer the question, you should:

1. Create a new RStudio project.
2. Copy the code from the [Data Lab 1 beak length script  &rarr;](lab1_beak_length_script.html) [click link] and paste it into a new script.
3. Modify the script to use the fast plant data `"fastplant_data.xlsx"`.

For a reminder on how to perform these steps, see [Data Lab 1, Part 4. Bluestem Data Assignment &rarr;](lab1_4_bluestem.html)

#### Fast plant data

You can download the fast plant data here:

<a href="fastplant_data.xlsx"><i class="fas fa-file-excel fa-5x"></i></a>

Each row in the dataset represents an individual plant.

The variables in the dataset are:

- **generation**. The generation the plant belonged to? (values include `"F0"` or `"F1"`)
- **trichome_number**. The number of trichomes the plant had. (values are numeric integers)
- **selected**. For the F0 generation, was the individual plant selected for breeding? (values include, `"yes"`, `"no"`, or `NA` if the plant was from the F1 generation)
- **seed_source** For the F1 generation, was the plant from the current year or a previous year (values include `"current_year"`, `"previous_year"`, or `NA` if the plant was from the F0 generation).